services:
  node-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    labels:
      jest_runner: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: "tail -f /dev/null"
